import pandas as pd
import os
import requests
import geojson
import boto3

def get_api_key(username, token):
    """
    Obtains an API key from the USGS M2M API using the login-token endpoint.

    Parameters:
    username (str): The USGS username.
    token (str): The USGS token. This token can be generated by logging into the
        "https://ers.cr.usgs.gov" Website.

    Returns:
    str: The API key for authentication.
    """

    login_url = "https://m2m.cr.usgs.gov/api/api/json/stable/login-token"
    
    payload = {"username": username, "token": token}
    response = requests.post(login_url, json=payload)

    if response.status_code == 200:
        return response.json().get("data", "")
    else:
        raise ValueError(f"Error obtaining API key: {response.text}")

def get_landsat_8_9_image_metadata(start_date, end_date, polygon, dataset,
    cloud_cover=None, satellite=None, sensor_id=None, processing_level=None,
    tier=None, max_results=50000, api_key=None):
    """
    Retrieves metadata for Landsat 8-9 images intersecting a given polygon
    within a date range. The acquisition date is used for filtering. This
    DataFrame can then be used to download the corresponding images.

    Parameters:
    start_date (str): Start date (inclusive) for the query (format: "YYYY-MM-DD")
    end_date (str): End date (inclusive) for the query (format: "YYYY-MM-DD")
    polygon (str): Polygon coordinates in "longitude latitude" format, comma-separated.
        Example: "-66.97 21.65, -66.91 20.76, -66.04 20.82, -66.04 21.61, -66.97 21.65"
    dataset (str): USGS dataset name for Landsat
        (e.g., "landsat_ot_c2_l1" for Landsat 8-9 Collection 2 Level 1).
    cloud_cover (int, optional): Maximum cloud cover percentage (0-100).
        Default is None (no filter).
    satellite (str, optional): The Landsat satellite. Options: "8", "9".
        Default is None (no filter).
    sensor_id (str, optional): The sensor identifier. Options: "OLI", "OLI_TIRS", "TIRS".
        Default is None (no filter).
    processing_level (str, optional): The processing level (e.g., "L1GS", "L1GT", "L1TP").
        Default is None (no filter).
    tier (str, optional): The tier level. Options: "T1" (Tier 1), "T2" (Tier 2), "RT" (Real-Time).
        Default is None (no filter).
    max_results (int, optional): Maximum number of results to retrieve.
        Default is 50000.
    api_key (str): USGS API key for authentication (required).

    Returns:
    pd.DataFrame: DataFrame containing metadata of the found images.
    """
    if api_key is None:
        raise ValueError("Se requiere un API key de USGS para la consulta. Inicie sesión para obtenerlo.")
    
    # Temporal filter (acquisition date)
    acquisition_filter = {
        'start': start_date,
        'end': end_date}

    # Construct spatial filter (GeoJSON)
    coords = [[float(x) for x in point.strip().split()] for point in polygon.split(',')]
    if coords[0] != coords[-1]:
        coords.append(coords[0])  # Ensure polygon is closed
    
    spatial_filter = {
        'filterType': 'geojson',
        'geoJson': geojson.Polygon([coords])
    }

    # Mapping of metadata names to their filter identifiers (filterId) in the API
    field_map = {
        "satellite": "61af93b8fad2acf5",
        "sensor_id": "5e81f14f85d499dc",
        "processing_level": "5e81f14fcf660794",
        "tier": "5e81f14fff5055a3"
    }
    
    # Allowed values for fields with predefined lists (according to metadata valueList)
    allowed_values = {
        "satellite": ["8", "9"],
        "sensor_id": ["OLI", "OLI_TIRS", "TIRS"],
        "processing_level": ["L1TP", "L1GT", "L1GS"],
        "tier": ["T1", "T2", "RT"],
    }

    # Simple validations for input values
    if satellite:
        # Accept satellite as int or str, convert to str for comparison
        satellite_value = str(satellite)
        if satellite_value not in allowed_values["satellite"]:
            raise ValueError(f"Invalid 'satellite' value: {satellite}. Allowed values: {allowed_values['satellite']}")
    if sensor_id:
        sensor_id_value = sensor_id.upper()
        if sensor_id_value not in allowed_values["sensor_id"]:
            raise ValueError(f"Invalid 'sensor_id' value: {sensor_id}. Allowed values: {allowed_values['sensor_id']}")
    if processing_level:
        processing_level_value = processing_level.upper()
        if processing_level_value not in allowed_values["processing_level"]:
            raise ValueError(f"Invalid 'data_type' value: {processing_level}. Allowed values: {allowed_values['processing_level']}")
    if tier:
        tier_value = tier.upper()
        if tier_value not in allowed_values["tier"]:
            raise ValueError(f"Invalid 'tier' value: {tier}. Allowed values: {allowed_values['tier']}")

    # Constructing search filters
    metadata_filters = []

    if satellite:
        metadata_filters.append({
            "filterId": field_map["satellite"],
            "filterType": "value",
            "value": satellite_value
        })
        
    if sensor_id:
        metadata_filters.append({
            "filterId": field_map["sensor_id"],
            "filterType": "value",
            "value": sensor_id_value
        })
    
    if processing_level:
        metadata_filters.append({
            "filterId": field_map["processing_level"],
            "filterType": "value",
            "value": processing_level_value
        })
    
    if tier:
        metadata_filters.append({
            "filterId": field_map["tier"],
            "filterType": "value",
            "value": tier_value
        })

    # Main scene filter construction
    scene_filter = {
        'spatialFilter': spatial_filter,
        'acquisitionFilter': acquisition_filter,
    }
    
    if metadata_filters:
        scene_filter["metadataFilter"] = {
            "filterType": "and",
            "childFilters": metadata_filters
    }

    if cloud_cover:
        scene_filter['cloudCoverFilter'] = {
            "min": 0,
            "max": cloud_cover,
            "includeUnknown": False
        }
    
    # Construct the payload for scene search
    search_payload = {
        'datasetName': dataset,
        'maxResults': max_results,
        'sceneFilter': scene_filter
    }

    # Make the request to the scene-search API
    url = "https://m2m.cr.usgs.gov/api/api/json/stable/scene-search"
    
    response = requests.post(
        url, json=search_payload, headers={'X-Auth-Token': api_key})
    result = response.json()

    if result.get('errorCode') is not None:
        raise RuntimeError(f"USGS API error {result['errorCode']}: {result.get('errorMessage')}")

    scenes = result.get('data', {}).get('results', [])
    df = pd.DataFrame(scenes)

    if df.empty:
        print("No se encontraron imágenes para los criterios especificados.")

    df['datasetName'] = dataset
    return df

def get_landsat_s3_url(display_id):
    """
    Constructs the AWS S3 URL for a given Landsat image based on its display ID.
    Supports Landsat Collection 2 (missions 4, 5, 7, 8, and 9), and all levels of
    processing.
    
    Parameters:
    display_id (str): The Landsat display ID
    (e.g., LC08_L1TP_012034_20240101_20240110_02_T1).
    
    Returns:
    str: S3 URL to the Landsat image folder.
    """
    
    # Splitting display_id
    display_parts = display_id.split('_')
    
    # Determining the processing level
    level = "level-1" if "L1" in display_parts[1] else "level-2"
    satellite_code = display_parts[0]  # e.g., "LC08"
    
    # Map satellite code to corresponding sensor folder
    sensor_folder_map = {
        "LC08": "oli-tirs",
        "LC09": "oli-tirs",
        "LE07": "etm",
        "LT05": "tm",
        "LT04": "tm"}
    sensor_folder = sensor_folder_map.get(satellite_code, "")
    
    # Extract path, row, and acquisition year
    path_row = display_parts[2]  # e.g., "026027"
    path = path_row[0:3]
    row_str = path_row[3:6]
    acquisition_date = display_parts[3]  # e.g., "20200827"
    year = acquisition_date[0:4]
    
    # Construct S3 prefix
    s3_prefix = f"collection02/{level}/standard/{sensor_folder}/{year}/{path}/{row_str}/{display_id}/"
    return s3_prefix
    
def download_landsat_products(df, target_directory):
    """
    Downloads all Landsat products corresponding to the displayId in the DataFrame
    created using the function get_landsat_image_metadata() function.
    Organizes each set of files in a directory named after the displayId inside
    the target directory and creates a ZIP archive of that directory.
    Assumes AWS credentials are configured in the environment
    (for Requester Pays access).
    
    Parameters:
        df (pd.DataFrame): DataFrame containing metadata of Landsat products.
        target_directory (str): Directory where all products will be stored.
        If it does not exist, it will be created.
    
    Returns:
        None (downloads and stores files locally).
    """

    # Initializing S3 client with configured credentials
    s3_client = boto3.client('s3') 
    bucket_name = "usgs-landsat"
    
    # Ensure the target directory exists
    if not os.path.isdir(target_directory):
        os.makedirs(target_directory, exist_ok=True)
    
    for idx, row in df.iterrows():
        display_id = row["displayId"]
        print(f"Procesando producto {display_id}...")
        
        # Construct S3 prefix using helper function
        prefix = get_landsat_s3_url(display_id)
        
        # Define product directory inside the target directory
        product_directory = os.path.join(target_directory, display_id)
        
        # Skip download if product directory already exists
        if os.path.isdir(product_directory):
            print(f" - La carpeta '{display_id}' ya existe, omitiendo descarga.")
            continue
        
        os.makedirs(product_directory)
        
        # List all objects under the prefix (handles pagination if >1000 objects)
        continuation_token = None
        download_paths = []
        
        while True:
            if continuation_token:
                response = s3_client.list_objects_v2(Bucket=bucket_name, Prefix=prefix,
                    ContinuationToken=continuation_token, RequestPayer="requester")
            else:
                response = s3_client.list_objects_v2(
                    Bucket=bucket_name, Prefix=prefix, RequestPayer="requester")
            
            if "Contents" in response:
                for obj in response["Contents"]:
                    download_path = obj["Key"]
                    # Skip empty "directory" markers if present
                    if download_path.endswith("/"):
                        continue
                    download_paths.append(download_path)
            
            if response.get('IsTruncated'):
                continuation_token = response.get('NextContinuationToken')
            else:
                break
        
        if not download_paths:
            print(f"No se encontraron objetos para {display_id}. Verifique el ID o la colección.")
            continue
        
        # Sequentially download each file if it does not already exist
        for download_path in download_paths:
            
            # Extract filename from download_path
            filename = os.path.basename(download_path) 
            local_path = os.path.join(product_directory, filename)
            if os.path.isfile(local_path):
                print(f" - Archivo '{filename}' ya existe, omitiendo descarga.")
            else:
                print(f" - Descargando '{filename}'...")
                s3_client.download_file(
                    bucket_name, download_path, local_path,
                    ExtraArgs={"RequestPayer": "requester"})
                
    print("Todas las descargas han finalizado.")
    